version: '3.5'
services:
  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.5
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./volumes/db:/var/lib/milvus/db
      - ./volumes/conf:/milvus/configs
      - ./volumes/logs:/milvus/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["milvus", "run", "standalone"]
